name: Deploy Laravel (NORMAL)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Frontend
        run: |
          npm install
          npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Composer
        run: composer install --no-dev --optimize-autoloader

      - name: Cleanup
        run: |
          rm -rf node_modules
          rm -rf tests
          rm -rf .git

      - name: 🚀 Deploy
        uses: SamKirkland/FTP-Deploy-Action@v2.0.0
        with:
          ftp_server: 145.223.108.5
          ftp_username: ${{ secrets.FTP_USERNAME }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          method: ftp
          port: 21
          local_dir: ./
          remote_dir: /domains/sihadir.smkn6solo.sch.id/AbsensiRPL/
          args: >
            --exclude-glob .git*
            --exclude-glob .env
            --exclude-glob node_modules/**
            --exclude-glob tests/**
            --exclude-glob storage/logs/**